using UnityEngine;

/// <summary>
/// Stores the 4-digit room code generated by the host before the lobby loads.
/// </summary>
public static class RoomCodeManager
{
    /// <summary>The current 4-digit room code (0 = none generated).</summary>
    public static int CurrentCode { get; private set; }

    /// <summary>Generate a new random 4-digit code (1000–9999).</summary>
    public static void GenerateCode()
    {
        CurrentCode = Random.Range(1000, 10000);
        Debug.Log($"Room code generated: {CurrentCode}");
    }

    /// <summary>Reset the code (e.g. on disconnect).</summary>
    public static void Reset()
    {
        CurrentCode = 0;
    }

    /// <summary>Formatted display string, e.g. "ROOM: 1234".</summary>
    public static string DisplayText => CurrentCode > 0 ? $"ROOM: {CurrentCode:D4}" : "";
}
